const IMAGES = {
  logoWithTitle: require('./logoWithTitle.png'),
  feature1: require('./feature1.png'),
  feature2: require('./feature2.png'),
  feature3: require('./feature3.png'),
  feature4: require('./feature4.png'),
  ScheduleIllustration: require('./ScheduleIllustration.png'),
  IsExploreDoneIllustration: require('./IsExploreDoneIllustration.png'),
  SplahScreen: require('./SplashScreen.png'),
  Illustration1: require('./Illustration1.png'),
  Illustration2: require('./Illustration2.png'),
  Bubblebackground: require('./bubblebackground.png'),
  BottomLogo: require('./BottomLogo.png'),
  ProfileInvite: require('./InviteFriend.png'),
  CountDays: require('./countdays.png'),
  MedSchool: require('./MedSchool.png'),
  ProfileInviteFriend: require('./InviteAFriend.png'),
  medImage: require('./med.png'),
  CompletlyPersonalized: require('./CompletlyPersonalized.png'),
  ScoreImprovement: require('./ScoreImprovement.png'),
  PercentileTutors: require('./PercentileTutors.png'),
  ProgressSchedule: require('./ProgressSchedule.png'),
  StudingCoach: require('./StudingCoach.png'),
  TickIconImage: require('./check.png'),
  GeenRemainingDaysBanner: require('./GreenRemainingDayBaneer.png'),
  RedRemainingDaysBanner: require('./RedRemainingDayBanner.png'),
  orangeRemainingDaysBanner: require('./OrnageRemainingDayBaneer.png'),
  AppleMusic: require('./AppleMusic.png'),
  GooglePodcast: require('./GooglePodcast.png'),
  Spotify: require('./Spotify.png'),
  Sticher: require('./Sticher.png'),
  Practice: require('./Practice.png'),
  Chemical: require('./Chemical.png'),
  MCAT_BAnnerImage: require('./MCatBanner.png'),
};

export default IMAGES;
