const FONTS = {
  ROBOTO_bold: 'Roboto-Bold',
  ROBOTO_boldItalic: 'Roboto-BoldItalic',
  ROBOTO_extraBold: 'Roboto-ExtraBold',
  ROBOTO_extraBoldItalic: 'Roboto-ExtraBoldItalic',
  ROBOTO_extraLight: 'Roboto-ExtraLight',
  ROBOTO_extraLightItalic: 'Roboto-ExtraLightItalic',
  ROBOTO_italic: 'Roboto-Italic',
  ROBOTO_light: 'Roboto-Light',
  ROBOTO_lightItalic: 'Roboto-LightItalic',
  ROBOTO_medium: 'Roboto-Medium',
  ROBOTO_mediumItalic: 'Roboto-MediumItalic',
  ROBOTO_regular: 'Roboto-Regular',
  ROBOTO_semiBold: 'Roboto-SemiBold',
  ROBOTO_semiBoldItalic: 'Roboto-SemiBoldItalic',
  ROBOTO_thin: 'Roboto-Thin',
  INTER_bold: 'Inter-Bold',
  INTER_boldItalic: 'Inter-BoldItalic',
  INTER_extraBold: 'Inter-ExtraBold',
  INTER_extraBoldItalic: 'Inter-ExtraBoldItalic',
  INTER_extraLight: 'Inter-ExtraLight',
  INTER_extraLightItalic: 'Inter-ExtraLightItalic',
  INTER_italic: 'Inter-Italic',
  INTER_light: 'Inter-Light',
  INTER_lightItalic: 'Inter-LightItalic',
  INTER_medium: 'Inter-Medium',
  INTER_mediumItalic: 'Inter-MediumItalic',
  INTER_regular: 'Inter-Regular',
  INTER_semiBold: 'Inter-SemiBold',
  INTER_semiBoldItalic: 'Inter-SemiBoldItalic',
  INTER_thin: 'Inter-Thin',
  INTER_thinItalic: 'Inter-ThinItalic',

  // RUBIK
  RUBIK_bold: 'Rubik-Bold',
  RUBIK_boldItalic: 'Rubik-BoldItalic',
  RUBIK_extraBold: 'Rubik-ExtraBold',
  RUBIK_extraBoldItalic: 'Rubik-ExtraBoldItalic',
  RUBIK_extraLight: 'Rubik-ExtraLight',
  RUBIK_extraLightItalic: 'Rubik-ExtraLightItalic',
  RUBIK_italic: 'Rubik-Italic',
  RUBIK_light: 'Rubik-Light',
  RUBIK_lightItalic: 'Rubik-LightItalic',
  RUBIK_medium: 'Rubik-Medium',
  RUBIK_mediumItalic: 'Rubik-MediumItalic',
  RUBIK_regular: 'Rubik-Regular',
  RUBIK_semiBold: 'Rubik-SemiBold',
  RUBIK_semiBoldItalic: 'Rubik-SemiBoldItalic',
  RUBIK_thin: 'Rubik-Thin',
  RUBIK_thinItalic: 'Rubik-ThinItalic',
};

export default FONTS;

export type FontFamilyType = keyof typeof FONTS;
